# Generated by Django 3.2.6 on 2021-08-15 13:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='eng_size',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
