# Generated by Django 3.2.6 on 2021-08-15 13:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210815_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2021), django.core.validators.MinValueValidator(1960)]),
        ),
    ]
