# Generated by Django 3.2.6 on 2021-08-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_car_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='title',
            new_name='car_maker',
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
