# Generated by Django 3.2.6 on 2021-08-17 11:32

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210816_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='header_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='images/default-img.jpg', force_format=None, keep_meta=True, quality=0, size=[500, 300], upload_to='images/'),
        ),
    ]
