# Generated by Django 3.2.6 on 2021-08-17 11:37

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_car_header_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='header_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='images/default-img.jpg', force_format=None, keep_meta=True, quality=0, size=[1920, 1080], upload_to='images/'),
        ),
    ]
