# Generated by Django 3.2.6 on 2021-08-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_car_header_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image2',
            field=models.ImageField(default='images/default-img.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='car',
            name='image3',
            field=models.ImageField(default='images/default-img.jpg', upload_to='images/'),
        ),
    ]
