# Generated by Django 3.2.6 on 2021-08-27 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20210827_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='kilometers',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(1000)]),
        ),
    ]
